/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppReportsListReportsRouteImport } from './routes/app/reports/list-reports'
import { Route as AppProfileSettingsRouteImport } from './routes/app/profile/settings'
import { Route as AppDashboardsListDashboardsRouteImport } from './routes/app/dashboards/list-dashboards'
import { Route as AppSettingUserIndexRouteImport } from './routes/app/setting/user/index'
import { Route as AppAdminWorkspaceIndexRouteImport } from './routes/app/admin/workspace/index'
import { Route as AppAdminUserIndexRouteImport } from './routes/app/admin/user/index'
import { Route as AppAdminReportIndexRouteImport } from './routes/app/admin/report/index'
import { Route as AppAdminGroupIndexRouteImport } from './routes/app/admin/group/index'
import { Route as AppAdminDatabaseIndexRouteImport } from './routes/app/admin/database/index'
import { Route as AppAdminDashboardIndexRouteImport } from './routes/app/admin/dashboard/index'
import { Route as AppAdminCategoryIndexRouteImport } from './routes/app/admin/category/index'
import { Route as AppAdminSettingSystemIndexRouteImport } from './routes/app/admin/setting/system/index'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/app/profile/',
  path: '/app/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/app/admin/',
  path: '/app/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsListReportsRoute = AppReportsListReportsRouteImport.update({
  id: '/app/reports/list-reports',
  path: '/app/reports/list-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileSettingsRoute = AppProfileSettingsRouteImport.update({
  id: '/app/profile/settings',
  path: '/app/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardsListDashboardsRoute =
  AppDashboardsListDashboardsRouteImport.update({
    id: '/app/dashboards/list-dashboards',
    path: '/app/dashboards/list-dashboards',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSettingUserIndexRoute = AppSettingUserIndexRouteImport.update({
  id: '/app/setting/user/',
  path: '/app/setting/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminWorkspaceIndexRoute = AppAdminWorkspaceIndexRouteImport.update({
  id: '/app/admin/workspace/',
  path: '/app/admin/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminUserIndexRoute = AppAdminUserIndexRouteImport.update({
  id: '/app/admin/user/',
  path: '/app/admin/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminReportIndexRoute = AppAdminReportIndexRouteImport.update({
  id: '/app/admin/report/',
  path: '/app/admin/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminGroupIndexRoute = AppAdminGroupIndexRouteImport.update({
  id: '/app/admin/group/',
  path: '/app/admin/group/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminDatabaseIndexRoute = AppAdminDatabaseIndexRouteImport.update({
  id: '/app/admin/database/',
  path: '/app/admin/database/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminDashboardIndexRoute = AppAdminDashboardIndexRouteImport.update({
  id: '/app/admin/dashboard/',
  path: '/app/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminCategoryIndexRoute = AppAdminCategoryIndexRouteImport.update({
  id: '/app/admin/category/',
  path: '/app/admin/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminSettingSystemIndexRoute =
  AppAdminSettingSystemIndexRouteImport.update({
    id: '/app/admin/setting/system/',
    path: '/app/admin/setting/system/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/app/dashboards/list-dashboards': typeof AppDashboardsListDashboardsRoute
  '/app/profile/settings': typeof AppProfileSettingsRoute
  '/app/reports/list-reports': typeof AppReportsListReportsRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/admin/category': typeof AppAdminCategoryIndexRoute
  '/app/admin/dashboard': typeof AppAdminDashboardIndexRoute
  '/app/admin/database': typeof AppAdminDatabaseIndexRoute
  '/app/admin/group': typeof AppAdminGroupIndexRoute
  '/app/admin/report': typeof AppAdminReportIndexRoute
  '/app/admin/user': typeof AppAdminUserIndexRoute
  '/app/admin/workspace': typeof AppAdminWorkspaceIndexRoute
  '/app/setting/user': typeof AppSettingUserIndexRoute
  '/app/admin/setting/system': typeof AppAdminSettingSystemIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/app/dashboards/list-dashboards': typeof AppDashboardsListDashboardsRoute
  '/app/profile/settings': typeof AppProfileSettingsRoute
  '/app/reports/list-reports': typeof AppReportsListReportsRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/admin/category': typeof AppAdminCategoryIndexRoute
  '/app/admin/dashboard': typeof AppAdminDashboardIndexRoute
  '/app/admin/database': typeof AppAdminDatabaseIndexRoute
  '/app/admin/group': typeof AppAdminGroupIndexRoute
  '/app/admin/report': typeof AppAdminReportIndexRoute
  '/app/admin/user': typeof AppAdminUserIndexRoute
  '/app/admin/workspace': typeof AppAdminWorkspaceIndexRoute
  '/app/setting/user': typeof AppSettingUserIndexRoute
  '/app/admin/setting/system': typeof AppAdminSettingSystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/app/dashboards/list-dashboards': typeof AppDashboardsListDashboardsRoute
  '/app/profile/settings': typeof AppProfileSettingsRoute
  '/app/reports/list-reports': typeof AppReportsListReportsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/admin/category/': typeof AppAdminCategoryIndexRoute
  '/app/admin/dashboard/': typeof AppAdminDashboardIndexRoute
  '/app/admin/database/': typeof AppAdminDatabaseIndexRoute
  '/app/admin/group/': typeof AppAdminGroupIndexRoute
  '/app/admin/report/': typeof AppAdminReportIndexRoute
  '/app/admin/user/': typeof AppAdminUserIndexRoute
  '/app/admin/workspace/': typeof AppAdminWorkspaceIndexRoute
  '/app/setting/user/': typeof AppSettingUserIndexRoute
  '/app/admin/setting/system/': typeof AppAdminSettingSystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/not-found'
    | '/app/dashboards/list-dashboards'
    | '/app/profile/settings'
    | '/app/reports/list-reports'
    | '/app/admin'
    | '/app/profile'
    | '/app/admin/category'
    | '/app/admin/dashboard'
    | '/app/admin/database'
    | '/app/admin/group'
    | '/app/admin/report'
    | '/app/admin/user'
    | '/app/admin/workspace'
    | '/app/setting/user'
    | '/app/admin/setting/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/not-found'
    | '/app/dashboards/list-dashboards'
    | '/app/profile/settings'
    | '/app/reports/list-reports'
    | '/app/admin'
    | '/app/profile'
    | '/app/admin/category'
    | '/app/admin/dashboard'
    | '/app/admin/database'
    | '/app/admin/group'
    | '/app/admin/report'
    | '/app/admin/user'
    | '/app/admin/workspace'
    | '/app/setting/user'
    | '/app/admin/setting/system'
  id:
    | '__root__'
    | '/login'
    | '/not-found'
    | '/app/dashboards/list-dashboards'
    | '/app/profile/settings'
    | '/app/reports/list-reports'
    | '/app/admin/'
    | '/app/profile/'
    | '/app/admin/category/'
    | '/app/admin/dashboard/'
    | '/app/admin/database/'
    | '/app/admin/group/'
    | '/app/admin/report/'
    | '/app/admin/user/'
    | '/app/admin/workspace/'
    | '/app/setting/user/'
    | '/app/admin/setting/system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  AppDashboardsListDashboardsRoute: typeof AppDashboardsListDashboardsRoute
  AppProfileSettingsRoute: typeof AppProfileSettingsRoute
  AppReportsListReportsRoute: typeof AppReportsListReportsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppAdminCategoryIndexRoute: typeof AppAdminCategoryIndexRoute
  AppAdminDashboardIndexRoute: typeof AppAdminDashboardIndexRoute
  AppAdminDatabaseIndexRoute: typeof AppAdminDatabaseIndexRoute
  AppAdminGroupIndexRoute: typeof AppAdminGroupIndexRoute
  AppAdminReportIndexRoute: typeof AppAdminReportIndexRoute
  AppAdminUserIndexRoute: typeof AppAdminUserIndexRoute
  AppAdminWorkspaceIndexRoute: typeof AppAdminWorkspaceIndexRoute
  AppSettingUserIndexRoute: typeof AppSettingUserIndexRoute
  AppAdminSettingSystemIndexRoute: typeof AppAdminSettingSystemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reports/list-reports': {
      id: '/app/reports/list-reports'
      path: '/app/reports/list-reports'
      fullPath: '/app/reports/list-reports'
      preLoaderRoute: typeof AppReportsListReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/settings': {
      id: '/app/profile/settings'
      path: '/app/profile/settings'
      fullPath: '/app/profile/settings'
      preLoaderRoute: typeof AppProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboards/list-dashboards': {
      id: '/app/dashboards/list-dashboards'
      path: '/app/dashboards/list-dashboards'
      fullPath: '/app/dashboards/list-dashboards'
      preLoaderRoute: typeof AppDashboardsListDashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/setting/user/': {
      id: '/app/setting/user/'
      path: '/app/setting/user'
      fullPath: '/app/setting/user'
      preLoaderRoute: typeof AppSettingUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/workspace/': {
      id: '/app/admin/workspace/'
      path: '/app/admin/workspace'
      fullPath: '/app/admin/workspace'
      preLoaderRoute: typeof AppAdminWorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/user/': {
      id: '/app/admin/user/'
      path: '/app/admin/user'
      fullPath: '/app/admin/user'
      preLoaderRoute: typeof AppAdminUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/report/': {
      id: '/app/admin/report/'
      path: '/app/admin/report'
      fullPath: '/app/admin/report'
      preLoaderRoute: typeof AppAdminReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/group/': {
      id: '/app/admin/group/'
      path: '/app/admin/group'
      fullPath: '/app/admin/group'
      preLoaderRoute: typeof AppAdminGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/database/': {
      id: '/app/admin/database/'
      path: '/app/admin/database'
      fullPath: '/app/admin/database'
      preLoaderRoute: typeof AppAdminDatabaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/dashboard/': {
      id: '/app/admin/dashboard/'
      path: '/app/admin/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/category/': {
      id: '/app/admin/category/'
      path: '/app/admin/category'
      fullPath: '/app/admin/category'
      preLoaderRoute: typeof AppAdminCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/setting/system/': {
      id: '/app/admin/setting/system/'
      path: '/app/admin/setting/system'
      fullPath: '/app/admin/setting/system'
      preLoaderRoute: typeof AppAdminSettingSystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  AppDashboardsListDashboardsRoute: AppDashboardsListDashboardsRoute,
  AppProfileSettingsRoute: AppProfileSettingsRoute,
  AppReportsListReportsRoute: AppReportsListReportsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppAdminCategoryIndexRoute: AppAdminCategoryIndexRoute,
  AppAdminDashboardIndexRoute: AppAdminDashboardIndexRoute,
  AppAdminDatabaseIndexRoute: AppAdminDatabaseIndexRoute,
  AppAdminGroupIndexRoute: AppAdminGroupIndexRoute,
  AppAdminReportIndexRoute: AppAdminReportIndexRoute,
  AppAdminUserIndexRoute: AppAdminUserIndexRoute,
  AppAdminWorkspaceIndexRoute: AppAdminWorkspaceIndexRoute,
  AppSettingUserIndexRoute: AppSettingUserIndexRoute,
  AppAdminSettingSystemIndexRoute: AppAdminSettingSystemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
