/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotFoundRouteImport } from './routes/NotFound'
import { Route as AppSettingUserIndexRouteImport } from './routes/app/setting/user/index'
import { Route as AppAdminWorkspaceIndexRouteImport } from './routes/app/admin/workspace/index'
import { Route as AppAdminUserIndexRouteImport } from './routes/app/admin/user/index'
import { Route as AppAdminReportIndexRouteImport } from './routes/app/admin/report/index'
import { Route as AppAdminGroupIndexRouteImport } from './routes/app/admin/group/index'
import { Route as AppAdminDashboardIndexRouteImport } from './routes/app/admin/dashboard/index'
import { Route as AppAdminSettingSystemIndexRouteImport } from './routes/app/admin/setting/system/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/NotFound',
  path: '/NotFound',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingUserIndexRoute = AppSettingUserIndexRouteImport.update({
  id: '/app/setting/user/',
  path: '/app/setting/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminWorkspaceIndexRoute = AppAdminWorkspaceIndexRouteImport.update({
  id: '/app/admin/workspace/',
  path: '/app/admin/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminUserIndexRoute = AppAdminUserIndexRouteImport.update({
  id: '/app/admin/user/',
  path: '/app/admin/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminReportIndexRoute = AppAdminReportIndexRouteImport.update({
  id: '/app/admin/report/',
  path: '/app/admin/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminGroupIndexRoute = AppAdminGroupIndexRouteImport.update({
  id: '/app/admin/group/',
  path: '/app/admin/group/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminDashboardIndexRoute = AppAdminDashboardIndexRouteImport.update({
  id: '/app/admin/dashboard/',
  path: '/app/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminSettingSystemIndexRoute =
  AppAdminSettingSystemIndexRouteImport.update({
    id: '/app/admin/setting/system/',
    path: '/app/admin/setting/system/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/NotFound': typeof NotFoundRoute
  '/login': typeof LoginRoute
  '/app/admin/dashboard': typeof AppAdminDashboardIndexRoute
  '/app/admin/group': typeof AppAdminGroupIndexRoute
  '/app/admin/report': typeof AppAdminReportIndexRoute
  '/app/admin/user': typeof AppAdminUserIndexRoute
  '/app/admin/workspace': typeof AppAdminWorkspaceIndexRoute
  '/app/setting/user': typeof AppSettingUserIndexRoute
  '/app/admin/setting/system': typeof AppAdminSettingSystemIndexRoute
}
export interface FileRoutesByTo {
  '/NotFound': typeof NotFoundRoute
  '/login': typeof LoginRoute
  '/app/admin/dashboard': typeof AppAdminDashboardIndexRoute
  '/app/admin/group': typeof AppAdminGroupIndexRoute
  '/app/admin/report': typeof AppAdminReportIndexRoute
  '/app/admin/user': typeof AppAdminUserIndexRoute
  '/app/admin/workspace': typeof AppAdminWorkspaceIndexRoute
  '/app/setting/user': typeof AppSettingUserIndexRoute
  '/app/admin/setting/system': typeof AppAdminSettingSystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/NotFound': typeof NotFoundRoute
  '/login': typeof LoginRoute
  '/app/admin/dashboard/': typeof AppAdminDashboardIndexRoute
  '/app/admin/group/': typeof AppAdminGroupIndexRoute
  '/app/admin/report/': typeof AppAdminReportIndexRoute
  '/app/admin/user/': typeof AppAdminUserIndexRoute
  '/app/admin/workspace/': typeof AppAdminWorkspaceIndexRoute
  '/app/setting/user/': typeof AppSettingUserIndexRoute
  '/app/admin/setting/system/': typeof AppAdminSettingSystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/NotFound'
    | '/login'
    | '/app/admin/dashboard'
    | '/app/admin/group'
    | '/app/admin/report'
    | '/app/admin/user'
    | '/app/admin/workspace'
    | '/app/setting/user'
    | '/app/admin/setting/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/NotFound'
    | '/login'
    | '/app/admin/dashboard'
    | '/app/admin/group'
    | '/app/admin/report'
    | '/app/admin/user'
    | '/app/admin/workspace'
    | '/app/setting/user'
    | '/app/admin/setting/system'
  id:
    | '__root__'
    | '/NotFound'
    | '/login'
    | '/app/admin/dashboard/'
    | '/app/admin/group/'
    | '/app/admin/report/'
    | '/app/admin/user/'
    | '/app/admin/workspace/'
    | '/app/setting/user/'
    | '/app/admin/setting/system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NotFoundRoute: typeof NotFoundRoute
  LoginRoute: typeof LoginRoute
  AppAdminDashboardIndexRoute: typeof AppAdminDashboardIndexRoute
  AppAdminGroupIndexRoute: typeof AppAdminGroupIndexRoute
  AppAdminReportIndexRoute: typeof AppAdminReportIndexRoute
  AppAdminUserIndexRoute: typeof AppAdminUserIndexRoute
  AppAdminWorkspaceIndexRoute: typeof AppAdminWorkspaceIndexRoute
  AppSettingUserIndexRoute: typeof AppSettingUserIndexRoute
  AppAdminSettingSystemIndexRoute: typeof AppAdminSettingSystemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/NotFound': {
      id: '/NotFound'
      path: '/NotFound'
      fullPath: '/NotFound'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/setting/user/': {
      id: '/app/setting/user/'
      path: '/app/setting/user'
      fullPath: '/app/setting/user'
      preLoaderRoute: typeof AppSettingUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/workspace/': {
      id: '/app/admin/workspace/'
      path: '/app/admin/workspace'
      fullPath: '/app/admin/workspace'
      preLoaderRoute: typeof AppAdminWorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/user/': {
      id: '/app/admin/user/'
      path: '/app/admin/user'
      fullPath: '/app/admin/user'
      preLoaderRoute: typeof AppAdminUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/report/': {
      id: '/app/admin/report/'
      path: '/app/admin/report'
      fullPath: '/app/admin/report'
      preLoaderRoute: typeof AppAdminReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/group/': {
      id: '/app/admin/group/'
      path: '/app/admin/group'
      fullPath: '/app/admin/group'
      preLoaderRoute: typeof AppAdminGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/dashboard/': {
      id: '/app/admin/dashboard/'
      path: '/app/admin/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/setting/system/': {
      id: '/app/admin/setting/system/'
      path: '/app/admin/setting/system'
      fullPath: '/app/admin/setting/system'
      preLoaderRoute: typeof AppAdminSettingSystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  NotFoundRoute: NotFoundRoute,
  LoginRoute: LoginRoute,
  AppAdminDashboardIndexRoute: AppAdminDashboardIndexRoute,
  AppAdminGroupIndexRoute: AppAdminGroupIndexRoute,
  AppAdminReportIndexRoute: AppAdminReportIndexRoute,
  AppAdminUserIndexRoute: AppAdminUserIndexRoute,
  AppAdminWorkspaceIndexRoute: AppAdminWorkspaceIndexRoute,
  AppSettingUserIndexRoute: AppSettingUserIndexRoute,
  AppAdminSettingSystemIndexRoute: AppAdminSettingSystemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
