# Config file for Air (hot reloading)

# Working directory
root = "."

# Build options
build = "go build -o ./tmp/main ."

# Command to run the application
cmd = "./tmp/main"

# Watch directories for changes
include = ["."]

# Exclude specific files or directories
exclude = ["tmp", "vendor", "node_modules", ".git", ".idea", ".vscode"]

# File extensions to watch
extensions = ["go", "tpl", "tmpl", "html"]